package server

import (
	"encoding/json"
	"fmt"
	"net/http"
	"strings"

	"dataWriter/src/spec"
)

type scaffoldRequest struct {
	SQL string `json:"sql"`
}

func handleScaffold(w http.ResponseWriter, r *http.Request) {
	var req scaffoldRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]string{"error": "invalid JSON: " + err.Error()})
		return
	}
	if req.SQL == "" {
		writeJSON(w, http.StatusBadRequest, map[string]string{"error": "sql is required"})
		return
	}
	text, err := buildScaffold(req.SQL)
	if err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]string{"error": err.Error()})
		return
	}
	writeJSON(w, http.StatusOK, map[string]string{"generators_go": text})
}

func buildScaffold(sql string) (string, error) {
	specs, err := spec.GetSpecFromString(sql)
	if err != nil {
		return "", fmt.Errorf("invalid SQL: %w", err)
	}

	tableName, _ := spec.GetSchemaTableNameFromSQL(sql)

	var b strings.Builder
	b.WriteString("// Code generated by data-writer scaffold. Edit freely.\n")
	fmt.Fprintf(&b, "// Task: %s\n", tableName)
	b.WriteString(`//
// How to use:
//   - Uncomment a function to override that column's default generator.
//   - Function name is column name in PascalCase (user_id -> UserId).
//   - Read sibling columns with ctx.Int64("user_id") etc — columns must
//     appear earlier in CREATE TABLE than the current one.
//   - Return value must match the column's Go type (see each stub).
//   - Return nil for NULL.

package user

import "dataWriter/src/gen"

`)

	for _, c := range specs {
		retType, placeholder := scaffoldReturnShape(c.SQLType)
		fmt.Fprintf(&b, "// Column: %s  SQL: %s  -> return %s or nil\n",
			c.OrigName, c.DisplaySQLType(), retType)
		fmt.Fprintf(&b, "// func %s(ctx *gen.Ctx) any {\n", snakeToPascal(c.OrigName))
		fmt.Fprintf(&b, "//     return %s\n", placeholder)
		fmt.Fprintf(&b, "// }\n\n")
	}

	return b.String(), nil
}

func scaffoldReturnShape(sqlType string) (retType, placeholder string) {
	switch sqlType {
	case "tinyint", "smallint", "mediumint", "int", "year":
		return "int32", "int32(0)"
	case "bigint":
		return "int64", "int64(0)"
	case "float", "double":
		return "float64", "float64(0)"
	case "char", "varchar", "text", "blob", "tinyblob", "varbinary":
		return "string", `""`
	case "timestamp", "datetime", "date", "time":
		return "time.Time", "time.Time{}"
	default:
		return "any", "nil"
	}
}

// snakeToPascal converts "user_id" -> "UserId", "device_finger" -> "DeviceFinger".
func snakeToPascal(name string) string {
	var b strings.Builder
	up := true
	for _, r := range name {
		if r == '_' {
			up = true
			continue
		}
		if up {
			if r >= 'a' && r <= 'z' {
				r = r - 'a' + 'A'
			}
			up = false
		}
		b.WriteRune(r)
	}
	return b.String()
}
