package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode"
)

func main() {
	in := flag.String("in", "", "directory to scan for user_gens*.go (required)")
	out := flag.String("out", "", "output path for registry_gen.go (required)")
	flag.Parse()

	if *in == "" || *out == "" {
		log.Fatal("both -in and -out are required")
	}
	if err := run(*in, *out); err != nil {
		log.Fatalf("codegen: %v", err)
	}
}

// genEntry holds a discovered generator function and the column name it maps to.
type genEntry struct {
	funcName   string
	columnName string
}

// directive records a "// gen:column <name>" comment and its line number.
type directive struct {
	line       int
	columnName string
}

// collectDirectives scans all comment groups in f for "// gen:column <name>"
// lines and returns them in file order.
func collectDirectives(fset *token.FileSet, f *ast.File) []directive {
	var out []directive
	for _, cg := range f.Comments {
		for _, c := range cg.List {
			text := strings.TrimPrefix(c.Text, "//")
			text = strings.TrimSpace(text)
			name, ok := strings.CutPrefix(text, "gen:column ")
			if !ok {
				continue
			}
			name = strings.TrimSpace(name)
			if name != "" {
				line := fset.Position(c.Slash).Line
				out = append(out, directive{line: line, columnName: name})
			}
		}
	}
	return out
}

// findDirective returns the column name from the latest directive whose line
// number is strictly less than declLine, or "" if none exists.
func findDirective(directives []directive, declLine int) string {
	latest := ""
	for _, d := range directives {
		if d.line < declLine {
			latest = d.columnName
		}
	}
	return latest
}

func run(in, out string) error {
	fset := token.NewFileSet()

	entries, err := os.ReadDir(in)
	if err != nil {
		return fmt.Errorf("read dir %s: %w", in, err)
	}

	var generators []genEntry

	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".go") {
			continue
		}
		if e.Name() == filepath.Base(out) || e.Name() == "doc.go" {
			continue
		}
		path := filepath.Join(in, e.Name())
		f, err := parser.ParseFile(fset, path, nil, parser.ParseComments|parser.SkipObjectResolution)
		if err != nil {
			return fmt.Errorf("parse %s: %w", path, err)
		}
		directives := collectDirectives(fset, f)
		for _, d := range f.Decls {
			fn, ok := d.(*ast.FuncDecl)
			if !ok {
				continue
			}
			if !matchesGenFuncSignature(fn) {
				continue
			}
			name := fn.Name.Name
			if !ast.IsExported(name) {
				continue
			}
			declLine := fset.Position(fn.Pos()).Line
			columnName := findDirective(directives, declLine)
			if columnName == "" {
				columnName = pascalToSnake(name)
			}
			generators = append(generators, genEntry{funcName: name, columnName: columnName})
		}
	}

	sort.Slice(generators, func(i, j int) bool {
		return generators[i].funcName < generators[j].funcName
	})

	var buf bytes.Buffer
	buf.WriteString("// Code generated by cmd/codegen. DO NOT EDIT.\n")
	buf.WriteString("package user\n\n")
	if len(generators) == 0 {
		buf.WriteString("// no user generators detected\n")
	} else {
		buf.WriteString("import \"dataWriter/src/gen\"\n\n")
		buf.WriteString("func init() {\n")
		for _, g := range generators {
			fmt.Fprintf(&buf, "\tgen.Register(%q, %s)\n", g.columnName, g.funcName)
		}
		buf.WriteString("}\n")
	}
	return os.WriteFile(out, buf.Bytes(), 0644)
}

// matchesGenFuncSignature reports whether fn has exactly:
//
//	func Name(ctx *gen.Ctx) any
func matchesGenFuncSignature(fn *ast.FuncDecl) bool {
	if fn.Recv != nil {
		return false
	}
	if fn.Type.Params == nil || len(fn.Type.Params.List) != 1 {
		return false
	}
	param := fn.Type.Params.List[0]
	star, ok := param.Type.(*ast.StarExpr)
	if !ok {
		return false
	}
	sel, ok := star.X.(*ast.SelectorExpr)
	if !ok || sel.Sel.Name != "Ctx" {
		return false
	}
	pkg, ok := sel.X.(*ast.Ident)
	if !ok || pkg.Name != "gen" {
		return false
	}
	if fn.Type.Results == nil || len(fn.Type.Results.List) != 1 {
		return false
	}
	ret := fn.Type.Results.List[0]
	id, ok := ret.Type.(*ast.Ident)
	if !ok || id.Name != "any" {
		return false
	}
	return true
}

// pascalToSnake converts "UserId" -> "user_id", "DeviceFinger" -> "device_finger".
// Insert underscore before an uppercase letter that follows a lowercase letter,
// then lowercase everything. Consecutive capitals (acronyms) stay together.
func pascalToSnake(name string) string {
	var b strings.Builder
	for i, r := range name {
		if i > 0 && unicode.IsUpper(r) {
			prev := rune(name[i-1])
			if unicode.IsLower(prev) {
				b.WriteByte('_')
			}
		}
		b.WriteRune(unicode.ToLower(r))
	}
	return b.String()
}
